name: Ramen-App
on:
  push:
    branches:
    - main
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GA_TOKEN}}
      - name: yarn install
        run: yarn install
      - name: eslint
        run: yarn lint
