name: Ramen-App
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  eslint:
  name: eslint / jest
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: yarn install
      run: yarn install
    - name: eslint review
      uses: reviewdog/action-eslint@v1
      with:
        reporter: github-pr-review
        eslint_flags: './**/*.{vue,ts,js}'
    - name: eslint
      run: yarn lint
