name: Ramen-App
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GA_TOKEN}}
      - name: yarn install
        run: yarn install
      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: './**/*.{vue,js}'
      - name: eslint
        run: yarn lint
