name: Lint-Check
on:
  pull_request:
    branches:
      - main
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GA_TOKEN}}
      - name: yarn install
        run: yarn install
      - name: lint test
        run: yarn lint:test
      - name: eslint
        run: yarn lint
